version: '3.7'

services: 

  api-node: 
    build:
      context: .
    container_name: api-node  
    ports:
      - "3001:3333"
    environment:
      - DATABASE_URL=file:./db.mysql
      - API_BASE_URL=http://localhost:3333
